// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UshJIGBpC6nZzXEmlYuinc1h6tYVmdM',
    appId: '1:146024581439:android:3416a09288896c1fa12b8a',
    messagingSenderId: '146024581439',
    projectId: 'bookabuddyadmin',
    storageBucket: 'bookabuddyadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT2S9QP2EsLDwr8bMaFxNiQxuGeJlaIWE',
    appId: '1:146024581439:ios:a14dbf5f77eb40c6a12b8a',
    messagingSenderId: '146024581439',
    projectId: 'bookabuddyadmin',
    storageBucket: 'bookabuddyadmin.firebasestorage.app',
    iosBundleId: 'com.grow4dreams.bookabuddyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT2S9QP2EsLDwr8bMaFxNiQxuGeJlaIWE',
    appId: '1:146024581439:ios:a14dbf5f77eb40c6a12b8a',
    messagingSenderId: '146024581439',
    projectId: 'bookabuddyadmin',
    storageBucket: 'bookabuddyadmin.firebasestorage.app',
    iosBundleId: 'com.grow4dreams.bookabuddyadmin',
  );
}
